añadir condicion para que no se añada el nombre de la app duplicada y cambiar de nuevo a merge, ya que con clone no se obtiene el historial de commits

diff --git a/.github/workflows/importarRepos.yaml b/.github/workflows/importarRepos.yaml
--- a/.github/workflows/importarRepos.yaml
+++ b/.github/workflows/importarRepos.yaml
@@ -28,22 +28,31 @@ jobs:
           shell: pwsh
           run: |
             $url = "https://${{github.actor}}:${{secrets.GitLabToken}}@gitlab.com/${{github.event.inputs.URL}}"
-            git clone $url oldRepo 
-            $app = Get-Content 'oldRepo/app.json' -Raw | ConvertFrom-Json
+
+            git remote add oldRepo $url
+            git fetch oldRepo
+            git merge oldRepo/main --allow-unrelated-histories -X theirs
+            if ($LASTEXITCODE -ne 0){
+              Write-Error "Se ha producido un error al importar el repositorio"
+              exit 1
+            }
+
+            $app = Get-Content './app.json' -Raw | ConvertFrom-Json
             $appName = $app.name
             if (-not(Test-Path $appName)){
               mkdir $appName
             }
-            Copy-Item -Path "oldRepo/*" -Destination $appName -Force -Recurse
-            rm 'README.md', '.gitignore'
 
-            Get-ChildItem -Path $appName | Where-Object {$_.Name -in @('README.md', '.gitignore')} | ForEach-Object {Move-Item -Path $_.FullName -Destination ${{github.workspace}} -Force}
-            
+            Get-ChildItem ${{github.workspace}} -Exclude .git, .github, $appName, .AL-Go, .gitignore, CODEOWNERS, README.md, Security.md, Support.md, 'al.code-workspace' | ForEach-Object {
+              Move-Item -Path $_.FullName -Destination $appName -Force
+            }
             $data = Get-Content ./.AL-Go/settings.json -Raw | ConvertFrom-Json
-            $data.appFolders += $appName
+            if (-not $data.appFolders.Contains($appName)) {
+              $data.appFolders += $appName
+            }
             $data | ConvertTo-Json -Depth 10 | Set-Content ./.AL-Go/settings.json
 
-            Remove-Item -Path "oldRepo" -Recurse -Force
+            git remote remove oldRepo
 
         - name: Commit y push a main
           run: | 
